#!/bin/bash

# Loop through all the arguments
for component in "$@"; do
  mkdir "$component"
  cd "$component" || exit
  touch "$component.tsx" index.ts
  echo "export default function $component() {return(<></>)}" > "$component.tsx"
  echo "export {default} from './$component'" > index.ts
  cd ..
done
